# Generated by Django 3.2.13 on 2022-05-30 14:20

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('bio', models.TextField(blank=True, max_length=800, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('social_youtube', models.URLField(blank=True, null=True)),
                ('social_website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
